from setuptools import setup, find_packages

setup(
    name='double-blind-token-system',
    version='1.0.0',
    description='Double-Blind Token System for Government Services',
    long_description=open('../README.md').read(),
    long_description_content_type='text/markdown',
    author='Open Source Community',
    author_email='opensource@example.com',
    url='https://github.com/yourusername/Double-Blind-Token-System-for-Government-Services',
    packages=find_packages(),
    install_requires=[
        'Django>=5.0.1',
        'djangorestframework>=3.14.0',
        'psycopg2-binary>=2.9.9',
        'python-decouple>=3.8',
        'cryptography>=42.0.0',
        'PyJWT>=2.8.0',
        'Pillow>=10.2.0',
        'transformers>=4.36.2',
        'torch>=2.1.2',
        'spacy>=3.7.2',
        'PyPDF2>=3.0.1',
        'pdfplumber>=0.10.3',
        'celery>=5.3.4',
        'redis>=5.0.1',
        'django-redis>=5.4.0',
        'django-cors-headers>=4.3.1',
        'gunicorn>=21.2.0',
        'prometheus-client>=0.19.0',
        'langchain>=0.1.0',
        'langchain-community>=0.0.10',
        'langgraph>=0.0.20',
        'langchain-core>=0.1.10',
        'faiss-cpu>=1.7.4',
        'sentence-transformers>=2.2.2',
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Intended Audience :: Government',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.11',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Security :: Cryptography',
    ],
    python_requires='>=3.11',
    keywords='government corruption transparency double-blind encryption ai rag',
    project_urls={
        'Bug Reports': 'https://github.com/yourusername/Double-Blind-Token-System-for-Government-Services/issues',
        'Source': 'https://github.com/yourusername/Double-Blind-Token-System-for-Government-Services',
        'Documentation': 'https://github.com/yourusername/Double-Blind-Token-System-for-Government-Services/tree/main/docs',
    },
)
